codeworld-api/src/CodeWorld/Color.hs

Fixed issue #160 - some functions forget their alpha channel.

Fixed functions forgetting the alpha channel

---

funblocks-client/src/Blockly/Workspace.hs
funblocks-client/src/Blocks/CodeGen.hs
funblocks-client/src/Main.hs
web/blocks.html
web/js/blockworld.js

Added an editor button that takes the user to code in the full CodeWorlds text UI - Issue #181 
Reduced some unnecessary parentheses - Issue #182 
Removed disable from the context menu - Issue #183 
Function names must now start with a lowercase letter (or underscore) and may only contain alphanumeric characters (and an underscore) - Issue #180

FunBlocks - Edit button and minor fixes

---

funblocks-client/src/Blocks/Types.hs
funblocks-client/src/Main.hs
web/blocks.html
web/env.html
web/js/blockworld.js
web/js/codeworld.js
web/js/codeworld_shared.js

Reduced code duplication in `codeworld.js` and `blockworld.js`. A new file `codeworld_shared.js` contains the shared code. This is currently a work in progress and I'm not entirely sure how to handle this properly in JavaScript.
Currently there are functions in `codeworld_shared.js` that depend on being defined (that is, implemented in `codeworld.js` or `blockworld.js`, example being signinCallback).
All of the features on both sites still appear working, though I don't think it is 'production ready'
Some other issues that were fixed:
* Undo history now gets reset upon new project or on loading a project - Issue #199 
* User defined function now correctly display in the toolbox - Issue #198
* Added a stop button - Issue #197 
* Fixed Gray button inputs - Issue #196 
* Disabling blocks no …

Reduced code duplication and some fixes

---

funblocks-client/src/Main.hs

This update addresses a few issues with the following changes (and also a few others) :
- Allow list comprehension variables to be used in top input - Issue #229 
- Don't accidentally rename other type blocks (including builtins) - Issue #228 
- Parameter blocks can only be used in their defining function - Issue #227 
- Renaming a function argument should update its occurrences - Issue #226 
- Code is generated on any change - Issue #225

FunBlocks Update - Bug fixes

---

funblocks-client/src/Blockly/Block.hs
funblocks-client/src/Blockly/DesignBlock.hs
funblocks-client/src/Blockly/TypeExpr.hs
funblocks-client/src/Blocks/Types.hs
web/blocks.html
web/blocktest.html
web/js/blocks/cw-event.js
web/js/blocks/cw-lists.js
web/js/blocks/cw-math.js
web/js/blocks/cw-pictures.js
web/js/blocks/cw-program.js
web/js/blocks/cw-text.js

This change includes:
- A new type system. 
- Uses most general unification on connection/disconnection to determine types.
Work still needs to be done on:
1. Local variables
2. Function calling blocks
3. First class functions

Funblocks Update - Initial work on new typing system

---

funblocks-client/src/Blocks/CodeGen.hs
web/blocks.html
web/blocktest.html
web/js/blocks/cw-lists.js
web/js/blocks/cw-tuples.js

This is pretty small for a pull request.
Changes:
1. Fix and move tuple blocks from Blockly to CodeWorld (#273)
2. Show numbers in the code generation as integers if they don't contain decimal places
3. Some refactoring on the local variable field

FunBlocks Update - Add Tuples

---

funblocks-client/src/Blockly/Workspace.hs
funblocks-client/src/Blocks/CodeGen.hs
funblocks-client/src/Blocks/Types.hs
funblocks-client/src/Main.hs
third_party/MaterialDesign/shape-plus.svg
web/blocks.html
web/ims/shape-plus.svg
web/js/blocks/cw-lists.js
web/js/blocks/cw-program.js
web/js/funblocks.js

1. Adds language syntax symbols and parentheses to blocks'
2. Automatically run hashed programs - #281
3. Disallow some type connections - #280 
4. Rename inputs to parameters in function dialog - #279
5. Duplicate parameter error is now less persistent - #278
6. Warnings are now shown automatically when inputs are disconnected.
7. #276
8. Guards in list comprehension are now type checked
9. Local variables are now inferred
10. Other minor fixes

FunBlocks Update - Language Syntax

---

funblocks-client/src/Blocks/CodeGen.hs

Changes:
1. Allows building empty data declarations #288 
2. Fixes syntax symbols on constructor #296 
3. Fix empty constructor block codegen ##295
4. Allow connecting blocks to a user defined function after it was used as a first class block #292

FunBlocks Update - Fix constructor 

---

codeworld-api/src/CodeWorld/Driver.hs

This is how I'm doing this right now. I don't know if this is an idiomatic way of overriding this value, but it works for me.
-Richard

Fixes #355: Allow port to be specified via CODEWORLD_API_PORT environment variable

---

web/js/blocks/cw-lists.js

Doesn't generalize anymore. Fixes #346

Improve type inference for list comprehension

---

Users.md

Information is based on an email to codeworld-users by Brendan.

Add an entry to Users.md for CodeDay.

---

codeworld-api/codeworld-api.cabal
codeworld-api/src/CodeWorld/Driver.hs
codeworld-api/src/CodeWorld/Prediction.hs
codeworld-api/src/test-prediction.hs
codeworld-game-api/src/CodeWorld/Message.hs
codeworld-game-server/codeworld-game-server.cabal
codeworld-game-server/src/Bot.hs
codeworld-game-server/src/CodeWorld/GameServer.hs
codeworld-game-server/src/Stresstest.hs

I gave #378 a shot. The code turned out to be not too large, which is good. A very very quick test runs, but the CPU usage was very high (possibly due to missing pings). Review and possibly merging would be nice. I will have less time over the weekend.

Local timestamps

---

codeworld-api/codeworld-api.cabal
codeworld-api/src/CodeWorld/Prediction.hs
codeworld-api/tests/prediction.hs

With more thoroughly quick-check based testing.

More finetuning to prediction code

---

web/gallery.html
web/gallery.json

There is now a column on the right with title, an optional description,
and an optional code link.
Moving the author information to the description is mostly to
demonstrate that feature, happy to revert that.
Also, I guess some descriptions could become more elaborate.

Improve gallery UI (#441)

---

codeworld-api/src/CodeWorld/CollaborationUI.hs
codeworld-api/src/CodeWorld/Driver.hs

Previously, in the driver, there was one constructor (`Setup`) used for
all stages of the setup, even if during some states some of the fields
did not make any sense. This is obviously not nice.
This now introduces a bit of type-level programming to index the UI
states by the setup phase (main, connecting, waiting), and allow the
driver to use different constructors.

Make the game join UI typesafe

---

web/help/codeworld.md

Saw it and thought I would submit a quick patch

Fixed a small "mistakem"

---

web/js/codeworld.js

This solves the problem with projectors and smart boards, as described in [Issue 414](https://github.com/google/codeworld/issues/414)

Use Ctrl-Up and Ctrl-Down to change the font size in the editor panel.

---

web/css/codeworld.css
web/env.html
web/js/codeworld.js

Button on the bottom pane displays a pop-out window with keyboard shortcuts on a simple table
Fixes issue #467

Pop-out window showing keyboard shortcuts

---

install.sh

I think we should update the dependency versions in `install.sh`. Like the node version, etc.

Update the dependency versions

---

web/css/codeworld.css
web/env.html
web/js/codeworld.js

* Video recording with the HTML5 MediaRecorder API
* Start and Stop Recording buttons to capture output and download
* Runs on Chrome and Firefox

Video exports with WebM streams

---

web/js/codeworld.js

* Resolve issues #513, #514 and #515

Change chunks reference error while recording

---

codeworld-compiler/test/testcase/test_animation/saved_error.txt
codeworld-compiler/test/testcase/test_animation/source.hs
codeworld-compiler/test/testcase/test_arguments/saved_error.txt
codeworld-compiler/test/testcase/test_colorName/saved_error.txt
codeworld-compiler/test/testcase/test_colorName/source.hs
codeworld-compiler/test/testcase/test_combiningAnimation/saved_error.txt
codeworld-compiler/test/testcase/test_combiningAnimation/source.hs
codeworld-compiler/test/testcase/test_ifCondition/saved_error.txt
codeworld-compiler/test/testcase/test_ifCondition/source.hs
codeworld-compiler/test/testcase/test_listComprehension/saved_error.txt
codeworld-compiler/test/testcase/test_listComprehension/source.hs
codeworld-compiler/test/testcase/test_missingBracket/saved_error.txt
codeworld-compiler/test/testcase/test_nakedExpression/saved_error.txt
codeworld-compiler/test/testcase/test_nesting/saved_error.txt
codeworld-compiler/test/testcase/test_nesting/source.hs
codeworld-compiler/test/testcase/test_numberType/saved_error.txt
codeworld-compiler/test/testcase/test_numberType/source.hs
codeworld-compiler/test/testcase/test_pointType/saved_error.txt
codeworld-compiler/test/testcase/test_pointType/source.hs
codeworld-compiler/test/testcase/test_simulation/saved_error.txt
codeworld-compiler/test/testcase/test_simulation/source.hs
codeworld-compiler/test/testcase/test_variableName/saved_error.txt

Update testcase output

---

codeworld-server/src/Main.hs
web/js/codeworld.js
web/js/codeworld_shared.js

I was running a bit late, so I am sending the fixes of the mentioned issues first.

Fixes #523, #527 and collisions of copyDirIfExists(-> copyFile)

---

web/help/codeworld.md

Mostly grammar updates, though I did add brief descriptions of the various shapes after each name in the list at the end of the drawing shapes section.

New updates

---

web/help/GuideIntro.md
web/help/GuideUnit1.md
web/help/GuideUnit2.md
web/help/GuideUnit4.md

This cleans up part 1, adds content ti part 2, and improves content in part 4 some

More Updates

---

web/help/GuideUnit5.md
web/help/GuideUnit8.md

Need more examples for interactions, including more on PointerPress, PointerRelease, and PointerMovement.

Added content to Interactions

---

web/help/GuideUnit6.md

Fix Simulation examples

---

web/help/GuideUnit6.md

vx was not in scope and was getting one extra output Parameter (Number Number Number Number) instead of Number Number Number

Fix typo/ function:

---

codeworld-api/src/CodeWorld/Driver.hs
codeworld-api/src/CodeWorld/Picture.hs

Add SolidPolygon

---

AUTHORS
CONTRIBUTORS

@kammitama5 
@parvmor 
@chelseaharper 
Any corrections before I add this?

Update AUTHORS and CONTRIBUTORS to reflect recent contributions

---

codeworld-api/src/CodeWorld/Driver.hs
codeworld-api/src/CodeWorld/Picture.hs

Start splitting Path into constructors

---

codeworld-api/codeworld-api.cabal
codeworld-api/src/CodeWorld/Driver.hs

add datatype SpeedSlider

---

codeworld-api/src/CodeWorld/Driver.hs

this is a start. 
I am getting this error:
```
• No instance for (RealFloat a)
arising from a use of ‘showFFloatAlt’
```

UI improvements to new SpeedSlider control

---

codeworld-api/src/CodeWorld/Driver.hs

Slider bugs

---

web/css/codeworld.css
web/env.html

make runner window resizable

---

codeworld-api/src/CodeWorld/Driver.hs

Part of debugger for simulations and interactions

Redo Button control and functionality

---

README.md

provide path for CONTRIBUTING.md in README.md

provide path for CONTRIBUTING.md

---

codeworld-api/src/CodeWorld/Driver.hs

ZoomIn Button (visible and functional)
ZoomOutButton (visible and functional)
ZoomResetViewButton (visible and functional)
Refactored animationControls
Need to take out commented code 2543 to 2550

Zoom controls

---

codeworld-api/src/CodeWorld/Driver.hs

Debug controls for drawingOf

---

codeworld-api/src/CodeWorld/Driver.hs

Add Zoom Slider

---

build.sh
install.sh
web/css/codeworld-cm.css
web/js/codeworld.js
web/js/codeworld_shared.js

Resolve doc on hover

---

AUTHORS
CONTRIBUTORS

Update AUTHORS and CONTRIBUTORS for recent changes

---

web/help/examples.md

* Fix Asteroids last score sometimes being higher than max score
* Simplify energy calculation
* Be nicer about thrusting when out of energy

Make various improvements to the Asteroids step function

---

web/blocks.html
web/css/codeworld.css
web/env.html
web/js/codeworld.js

Resolve Better sync code editor with the running program

---

build.sh
codeworld-compiler/src/CodeWorld/Compile.hs
web/css/lint.css
web/env.html
web/js/codeworld.js

 Continuous highlighting of syntax errors #134 

---

install.sh

Place popups relatively to target instead of mouse

---

web/js/codeworld.js
web/js/doc.js

Add position support for doc popup.

---

format.sh
third_party/details-element-polyfill/LICENSE
third_party/details-element-polyfill/details-element-polyfill.js
web/blocks.html
web/css/codeworld.css
web/env.html
web/js/codeworld.js
web/js/codeworld_shared.js
web/js/details-element-polyfill.js
web/js/run.js

Closes #764 
I took style for errors/log/warnings from firefox console.

More formatted console output

---

web/js/funblocks.js

PR contain fix for #854, but funblocks still does not work for me 
```
ReferenceError: Blockly is not defined[Learn More] funblocks.js:208:11
getWorkspaceXMLText http://127.0.0.1:8080/js/funblocks.js:208 containsUnsavedChanges http://127.0.0.1:8080/js/funblocks.js:216 isEditorClean http://127.0.0.1:8080/js/funblocks.js:220 updateUI http://127.0.0.1:8080/js/funblocks.js:367 cancelMove http://127.0.0.1:8080/js/codeworld_shared.js:703 discoverProjects_ http://127.0.0.1:8080/js/codeworld_shared.js:635 discoverProjects http://127.0.0.1:8080/js/funblocks.js:570 onAuthDisabled http://127.0.0.1:8080/js/codeworld_shared.js:581 init http://127.0.0.1:8080/js/codeworld_shared.js:601 onreadystatechange http://127.0.0.1:8080/js/codeworld_shared.js:40 
/ UI Layout Callback Error
The center onresize_end …
```

Replace addToMessage function in funblocks.

---

web/css/codeworld-cm.css
web/js/codeworld-mode.js

Add layout markers into codeworld-mode

---

web/help/GuideUnit5.md

Fix non-exhaustive patterns in examples for Guide - Part 5: State

---

codeworld-api/codeworld-api.cabal
codeworld-api/src/CodeWorld/CanvasM.hs
codeworld-api/test/Main.hs

WIP Fix broken time-step ellision

---

web/css/codeworld-cm.css
web/js/codeworld-mode.js
web/js/codeworld.js
web/js/codeworld_shared.js

closes #850 
The gif give a brief idea abut the progress. I dont understand where am I going wrong with the CSS? The tooltip should be perfectly solid, I copied the styles from ```CodeMirror-hover-tooltip``` class.

WIP (Add tooltip for inline functions) 

---

funblocks-client/src/Blocks/Parser.hs
web/blocks.html
web/js/blocks/cw-lists.js

Adds a ++ block referenced in #339

Adds ++ to list blocks

---

web/css/doc.css
web/env.html
web/help/codeworld.shelf
web/help/editor-haskell.md
web/help/editor.md
web/help/haskell.shelf
web/js/codeworld.js

Resolve 884

---

build.sh
third_party/MaterialDesign/content-copy.svg
third_party/MaterialDesign/content-cut.svg
third_party/MaterialDesign/content-paste.svg
third_party/MaterialDesign/content-save.svg
third_party/MaterialDesign/magnify.svg
third_party/MaterialDesign/redo.svg
third_party/MaterialDesign/undo.svg
third_party/codemirror-buttons/LICENSE.md
third_party/codemirror-buttons/LOCAL_CHANGES.diff
third_party/codemirror-buttons/buttons.js
web/css/codeworld-cm.css
web/env.html
web/ims/content-copy.svg
web/ims/content-cut.svg
web/ims/content-paste.svg
web/ims/content-save.svg
web/ims/magnify.svg
web/ims/redo.svg
web/ims/undo.svg
web/js/cm_addons/codemirror-buttons/buttons.js
web/js/codemirror-buttons/buttons.js
web/js/codeworld.js

Toolbar with naive clipboard.

---

web/help/examples.md

Currently, when holding the up arrow while out of energy, not only do you
not get any thrust, but you also don't recover any energy. Fix this by
turning off thrust when energy runs out, until it either fills all the way
back up, or the player releases the key.

Add a cooldown to the Asteroids example

---

web/css/theme-variables.css

Make mismatched bracked highlight red in dark mode

---

web/css/doc.css
web/css/theme-variables.css

Quick fix for haddock styles in dark mode.

---

codeworld-base/src/Extras/Cw.hs
codeworld-base/src/Extras/Util.hs

I have implemented a simple zoomable graph at the request of a teacher, who was really interested in using CodeWorld for graphing functions but needed ranges beyond -10 and 10.

Zoomable graphs and a couple of fixes and additions

---

codeworld-base/src/Extras/Cw.hs

Added two new functions: `customGraph` to create graphs with arbitrary widths and heights, and `tree` to draw trees.

customGraph and tree

---

codeworld-base/src/Extras/Cw.hs
web/js/codeworld_shared.js

The only real commit here is a bug fix in Extras.Cw.graphed. The other commits are the result of my merging upstream.

Extras - Fixed bug in graphed

---

build.sh
codeworld-server/codeworld-server.cabal
codeworld-server/src/Main.hs
codeworld-server/src/Migration.hs
codeworld-server/src/Util.hs
web/js/codeworld_local_auth.js

Migrate project directory structure for codeworld-server

---

web/css/codeworld.css
web/js/codeworld.js
web/js/codeworld_shared.js
web/js/funblocks.js

I forgot to branch, so this code also contains changes from #992 
Fixes #991

Do not select node until warnIfUnsaved resolved

---

web/css/codeworld.css
web/js/codeworld.js
web/js/codeworld_shared.js
web/js/funblocks.js

Return asterisk to navigation bar in tree view.

---

codeworld-api/src/CodeWorld/Driver.hs

Refactor DrawState

---

codeworld-api/src/CodeWorld/Driver.hs

Turn NodeId into a newtype, refactor findTopShape

---

codeworld-api/src/CodeWorld/Driver.hs

CW.Driver: Join Drawer functions with their type signatures

---

codeworld-api/codeworld-api.cabal

codeworld-api: Fix unit-tests build-depends

---

codeworld-api/codeworld-api.cabal
codeworld-api/src/CodeWorld/Driver.hs

This pull request attempts to merge the Inspect debugger with Reflex.  It doesn't yet work.  I just get a black screen, which apparently happens when there's some kind of dependency cycle in the reflex code.

[WIP] Inspect-style debugging for reflex FRP code.

---

codeworld-api/src/CodeWorld/EntryPoints.hs
codeworld-api/src/CodeWorld/Picture.hs
codeworld-api/src/CodeWorld/Reflex.hs

Hello @cdsmith, reading your 2 recent blog posts about Reflex on codeworld got me super-excited about reflex. Here's a couple of haddock markup fixes. If you find providing examples useful, I can add more.

Fix haddock markup for codeworkld apis, add examples

---

.travis.yml

This should solve the problem of build time-outs.  Not sure if this will pass, yet: https://travis-ci.org/peterbecich/codeworld/builds/604293274

Travis-CI build stages

---

.travis.yml

Incorrect environment variable was used.

Correct Travis caching

---

.travis.yml

https://github.com/google/codeworld/issues/1229

attempt to improve Travis CI reliability

---

codeworld-base/src/Internal/Picture.hs

Mention how the negative factors work. They were already covered in
the guide but not directly in the function documention.
This should help a little until Reflections #757 are addressed fully.

Expand haddock of scaled and dilated.

---

.travis.yml
README.md

https://github.com/google/codeworld/issues/1229
I just read https://docs.travis-ci.com/user/caching/#caches-and-build-matrices 
This PR is another attempt to prevent cache errors.

Travis reliability

---

.travis.yml
stack.yaml

and another improvement to the Travis config.

Fix Stack dependency for Ormolu

---

codeworld-available-pkgs/codeworld-available-pkgs.cabal

A little extra for mwc-random, bringing common distributions and their sampling.

Add mwc-probability

---

web/css/codeworld-cm.css
web/js/codeworld-mode.js

Detect & highlight non-matching closing brackets

---

web/css/codeworld.css
web/js/codeworld_shared.js

Append output instead of entirely replacing it every time.

---

.eslintrc.yml
web/blockframe.html
web/blocks.html
web/css/codeworld.css
web/doc.html
web/env.html
web/js/codeworld.js
web/js/codeworld_shared.js
web/js/doc.js
web/js/funblocks.js
web/js/treedialog.js
web/js/utils/alert.js
web/js/utils/auth.js
web/js/utils/directoryTree.js
web/js/utils/html.js
web/js/utils/index.js
web/js/utils/network.js
web/js/utils/object.js

I aimed to just make things work again after moving methods around and getting rid of inlined click handlers, without attempting to introduce any extra changes. Both main editor and blocks appear to be functional for me, although I didn't spend a lot of time testing.

Convert core JS files into modules

---

web/js/codeworld.js
web/js/codeworld_shared.js
web/js/funblocks.js

Create functions for updating doc title and project's change mark

---

web/js/codeworld.js
web/js/codeworld_shared.js
web/js/funblocks.js
web/js/utils/auth.js
web/js/utils/directoryTree.js

Load all nested items under a given folder to enable proper drag'n'drop functionality.

---

web/js/utils/auth.js

Add missing imports to the auth module + slight refactor.

---

web/css/doc.css
web/help/codeworld.shelf
web/js/doc.js

Reorganize guide's navbar.

---

web/blockframe.html
web/blocks.html
web/css/gallery.css
web/doc.html
web/env.html
web/gallery.html
web/js/blockframe.js
web/js/codeworld.js
web/js/codeworld_shared.js
web/js/debugmode.js
web/js/doc.js
web/js/funblocks.js
web/js/gallery.js
web/js/run.js
web/run.html

Remove inline js and css

---

.travis.yml

Delete Stack `pantry.sqlite3` file at beginning

attempt to fix Travis CI

---

web/js/codeExplorer.js
web/js/codeworld.js

Explicitely pass messages to codeExplorer module
