google/codeworld

- funblocks-client/src/Blockly/Block.hs
- funblocks-client/src/Blockly/Connection.hs
- funblocks-client/src/Blockly/DesignBlock.hs
- funblocks-client/src/Blockly/Workspace.hs
- funblocks-client/src/Blocks/CodeGen.hs
- funblocks-client/src/Blocks/Types.hs
- funblocks-client/src/Main.hs
- web/blocks.html
- web/css/blockly.css
- web/css/funblocks.css
- web/js/blockworld.js
Let blocks added. When a let definition block is added to the canvas a corresponding call block gets added to the toolbox.
Minor bug: The correct type of the block gets displayed when it is dragged to the canvas, however in the toolbox it is always displayed with a polymorphic connector.
The following issues were fixed:
1. Validation for number block - Issue #176 
2. Escaping for text block - Issue #175 
3. Non entry point, stray blocks get disabled - Issue #173 
4. Run window and code get cleared on project load - Issue #171 
5. Warning is shown when there are unsaved changes that could be lost - Issue #170 
6. Improved visual indication for disconnected inputs: Only single block gets highlighted with a warning popup indicating that the block contains disconnected inputs. The block gets …
> FunBlocks update - Let blocks and fixes

- .gitignore
- funblocks-client/src/Blocks/CodeGen.hs
- funblocks-client/src/Blocks/Types.hs
- web/blocks.html
- web/js/blockworld.js
FunBlocks now warns the user when he tries to leave the page if there are unsaved changes, as per issue #170 
Updated Blockly to handle let variable connecting and disconnecting better. 
The type of all child blocks change when the definition type changes. Child blocks also bump away if there is a type mismatch.
The type changes to polymorphic upon disconnect.
This fixes issue #186. Issue #185 is also fixed, though no additional recursion checking is done.
Added a percentage block. RGBA, Gray and Scaled also now use this percentage block as shadow blocks in the toolbox. This is work for issue #190.
The RGBA block was also fixed.
> Fixed let blocks, added percentage block, warn when leaving page

- funblocks-client/src/Blockly/Workspace.hs
- funblocks-client/src/Main.hs
Disable disconnected blocks upon creation event as well - Issue #205
Blockly is updated. Call blocks can't be created from the context menu anymore - Issue #205 . I also think it is better this way, as they are automatically disabled anyway. 
a.getProcedure is correctly called now - Issue #203. Block type changing for the Let definition is still a problem and unchanged.
They can still be created from the toolbar and copying, pasting works now as well.
Added an error message if there are no top level program blocks. This improves point 3. in issue #169
> FunBlocks update - minor fixes

- install.sh
Fix #215: Install from 0.2 branch of ghcjs-dom
Corresponds to versions of ghcjs-dom before package was split into four separate subpackages
> Fix #215: Install from 0.2 branch of ghcjs-dom

- README.md
- codeworld-api/codeworld-api.cabal
- codeworld-api/src/CodeWorld/Driver.hs
The stand-alone mode now works, including animation and interaction. There might be rough edges, but in principle I think it can be merged. Or at least be tested and reviewed.
I did not change the default assignment of the `ghcjs` flag, but it probably should: Whoever runs `cabal install codeworld-api` probably wants the stand-alone version, and the other version is probably always built by the `build.sh` script, which is a convenient place to specify `-fghcjs`.
> Stand alone mode

- funblocks-client/src/Blockly/Workspace.hs
- funblocks-client/src/Blocks/CodeGen.hs
- funblocks-client/src/Main.hs
- web/js/blocks/cw-event.js
- web/js/blocks/cw-lists.js
- web/js/blocks/cw-pictures.js
I'm switching to fully using the Hindley Milner type inference, which is enabled by default in this.
Each expression is tagged with a connection, which is updated afterwards. Unconnected inputs have polymorphic type. 
Each block now also has a lambda expression, for example, the list create block might have the expression 
```
a:(b:(c:[]))
```
Builtin function types are added to the environment, and blocks are function application on them.
For example circle is added to the environment as 
```
circle : Number -> Picture
```
the circle block either applies the connected expression or `forall a. a` if the input is disconnected, which yields something such as
```
(circle)(3)
```
This new behavior is much less adhoc and extending it to new blocks only requires defining the appropriate …
> FunBlocks Update - Hindley Milner and saving loading

- funblocks-client/src/Blocks/CodeGen.hs
- funblocks-client/src/Blocks/Parser.hs
This update addresses the following issues:
1. Top case expression now gets inferred - #304
2. Fix bug causing #303 and 
3. Prevent #302 by renaming internal `ev` to `1ev`
4. Fix case codegen #301 and #297 
6. Fix constructor bug - #291
I moved escape to the parsing code, in the event we want to add a block with a character that shouldn't get escaped. (I wanted a newline character but it doesn't get drawn, so i'm not sure if this is actually necessary)
> FunBlocks Update - User data type fixes

- funblocks-client/src/Blocks/Types.hs
- funblocks-client/src/Main.hs
- web/blocks.html
- web/help/blockframe.html
- web/js/blocks/cw-logic.js
- web/js/blocks/cw-pictures.js
- web/js/blocks/cw-text.js
- web/js/blocks/init.js
- web/js/funblocks.js
This change set addresses the following issues:
- Picture combine (&) and text concat (<>) don't disconnect their blocks anymore - #329. However they do still lose their shadow arguments (#309).
- Certain words can be reserved - #351. Custom words can be reserved with `Blockly.UserTypes.userReservedNames` in web/js/blocks/init.js. Codeworld functions defined using `defineFunction` are also reserved.
- Collapsed blocks don't show polymorphic indicators anymore, fixing #347.
- A block in the toolbox must now be dragged a certain distance in order to be created - issue #327.
- Programs that contain errors can be shared after they are run - issue #300 
I'm still investigating #337. The effect exists with other blocks as well; the displacement happens to the polymorphic color indicator; …
> Blocks Update - Bug fixes

- funblocks-client/src/Blocks/CodeGen.hs
- funblocks-client/src/Blocks/Parser.hs
- web/js/blocks/cw-pictures.js
- web/js/blocks/cw-text.js
This update addresses issue #370. A warning is also shown when these block have less than two inputs.
Additionally, the updated Blockly shows an `=` sign for the first input when defining a user data type (issue #365).
A minor change is that `<>` is now used for `Text` concatenation in the Parsing and CodeGen code in place of my own `++` that was defined for appending `Text`
> Fix errors caused when text concatenation and picture combine have less than 2 inputs

- codeworld-api/src/CodeWorld/Driver.hs
- codeworld-game-server/codeworld-game-server.cabal
- codeworld-game-server/src/CodeWorld/GameServer.hs
- codeworld-game-server/src/Main.hs
JSON-interface for statistics, more efficient code, etc. (see individual commit messages.)
> Game server improvements

- codeworld-game-api/src/CodeWorld/Message.hs
- codeworld-game-server/codeworld-game-server.cabal
- codeworld-game-server/src/Stresstest.hs
```
$ ./codeworld-game-stresstest --help
codeword-game-stresstest - a stresstest for codeworld-gameserver
Usage: codeworld-game-stresstest [-c|--clients N] [-e|--events M]
[--hostname HOSTNAME] [--port PORT]
[--path PATH]
CodeWorld gameserver stresstest client
Available options:
-h,--help                Show this help text
-c,--clients N           Number of clients (>=1) (default: 3)
-e,--events M            Number of events every client should
send (default: 100)
--hostname HOSTNAME      Hostname (default: "0.0.0.0")
--port PORT              Port (default: 9160)
--path PATH              Path (default: "gameserver")
$ codeworld-game-stresstest -c 50 -e 1000
All clients got consistent data.
Events sent:         50000
Running time was:    49453.714961000005ms
Requests per second: …
```
> Add a stress test client for the game server

- codeworld-api/src/CodeWorld/Picture.hs
The definitions for `solidCircle`, `thickCircle` and `circle` call functions `sector`, `thickCircle` and `arc`. These functions take angles in radians while the circle related functions specify angle in degrees. So 360 is actually treated as 360 radians.
> Write angles in radians instead of degrees

- web/js/doc.js
I heard about your project through the Summer of Haskell site and wanted to help out. Hopefully this small change makes the help a little easier to use.
A link now appears at the top of the help allowing users to open the guide in a new page. Some additional code keeps the pages "linked" so clicking on code samples will still call `loadSample` on the other window.
Another design would have been to put a popout button on the top of the SweetAlert, but I think avoiding a top bar would help save space and keep formatting consistent between browsers. Hopefully I'm not breaking any localization rules by hardcoding the link text.
> Fix #457 Allow Users to Open Help in New Tab

- web/help/codeworld.md
The current Guide menu looks like this : 
Due to this, the vertical x scrollbar gets added which looks conspicuous, especially in hand held devices . The current PR makes sure the image size is that of the menu, hence improves viewability in all types of devices:
The overflow-x scrollbar which was not needed will be removed by this PR.
> Fix image size in Guide menu, fixes overflow-x

- web/js/codeworld_shared.js
This Pull Request mainly solves the issue #420. The main problem, in that case, is with the wrong value of `token`. 
Consider an example- If I put 4 spaces and then try to make insertion at position 2 using autocorrect, it add the selected value at the end of four space because of the wrong value in `token.end` with respect to the cursor position. I updated the function for that in `web/js/codeworld_shared.js`.
> Resolve issue, autocomplete inserts at the wrong place when used between two spaces #420

- README.md
As per [the last line of `install.sh`](https://github.com/google/codeworld/blob/master/install.sh#L180), `./build.sh` is already called once . Avoid rerunning build.sh, but needs to be mentioned since someone might want to build explicitly and that detail should be mentioned.
Edits are welcome. We can also remove `./build.sh` from install.sh as an alternative.
> Avoid rerunning build script

- codeworld-api/codeworld-api.cabal
- codeworld-api/src/CodeWorld.hs
- codeworld-api/src/CodeWorld/Color.hs
- codeworld-base/src/Internal/Color.hs
- codeworld-base/src/Internal/Exports.hs
Simple implementation of this request: https://github.com/google/codeworld/issues/436
A function `rainbow` takes a parameter `speed`.  With a speed of 1.0, `rainbow` produces an infinite list that cycles through the HSL color spectrum in 100 indices.  With a speed of 0.5, this cycle should occur in 200 indices (unless I'm making a trivial algebra mistake :) ).
> Infinite list of colors

- codeworld-base/src/Internal/Num.hs
With reference to the issue #495, I made a correction in the error message for acos function.
> Corrected error typo in base- Num.hs for acos

- codeworld-server/codeworld-server.cabal
- codeworld-server/src/Build.hs
- codeworld-server/src/ErrorSanitizer.hs
- web/js/codeworld_shared.js
This P.R. mainly refers to:
Shifting of regex module from Javascript to Haskell.
I have used `subRegex` function from `Text.Regex` library in order to replace regex patterns in Haskell.
> Regex shift1

- codeworld-api/src/CodeWorld/Driver.hs
- web/css/runner.css
- web/js/codeworld.js
- web/js/codeworld_shared.js
- web/js/debugmode.js
- web/run.html
This PR adds support for debugmode to animationOf, simulationOf and interactionOf. The animationOf and simulationOf entry must be paused before inspecting. The interactionOf entrypoint will automatically pause by clicking Inspect and will not receive events while paused. This PR should also fix bugs #521, #516 and #517.
The `isPointInStroke` function is used for strokes, consistent with `isPointInPath` for solid shapes. Line numbers in infobox are better aligned and names link to their documentation. The inspect button will only show if available. Pausing was originally implemented by holding an MVar that was released when leaving debugmode, but is now implemented as wrappers around states and events that is cleaner and requires less changes. An unreported bug where text couldn't be …
> Add debugmode support to animationOf, simulationOf and interactionOf

- install.sh
Addresses Issue #546
The GHC build failed due to a missing C++ preprocessor. This fix includes `g++` in the install script.
> Include C++ compiler installation in install.sh

- base.sh
- install.sh
This works on my machine, and it's possible that I have some dependencies already installed.
It runs OK, but when I run the logo demo I get the error messages:
Line 30, Column 48: error: Missing parentheses in function application
Line 42, Column 31: error: Missing parentheses in function application
Line 43, Column 31: error: Missing parentheses in function application
even though the logo seems to be produced correctly.
> Add OS X package manager and GHC architecture detection

- web/help/GuideUnit1.md
"Radius of\n2.  Blah..." was apparently getting parsed by Markdown as the start of an enumeration.
> Fix bad markdown formatting

- codeworld-api/src/CodeWorld/Driver.hs
- codeworld-api/src/CodeWorld/Picture.hs
```solidPolygon``` function still uses ```SolidPolygon``` constructor and ```solidClosedCurve``` uses SolidClosedCurve. It type-checks, but not sure if I did anything wrong ;/
> Add SolidClosedCurve

- codeworld-api/src/CodeWorld/Driver.hs
- codeworld-api/src/CodeWorld/Picture.hs
What needs to be removed here? I've initially just passed ```0``` for Arc and Thickline has ```w``` and made it type-check.
> Splitting Arc and ThickArc in Picture - type checks first attempt

- base.sh
- install.sh
This change updates `install.sh` to install Node 8 instead of (now-deprecated) Node 7. It also runs using `set -euo pipefail` ("strict mode") in order to fail fast. I also added a `--quiet` switch to the `run` function to get rid of errors when using `run` in a pipeline.
> Fixes #639: Use Node 8.x and run in Bash strict mode

- codeworld-api/src/CodeWorld/Driver.hs
stepButton in simulationOf was in wrong place.
This moves the button to a better place.
> Fix simulationOf stepButton

- web/blocks.html
- web/css/codeworld.css
- web/env.html
Fixes #732 by allowing the toolbar to wrap and also taking it out of the jQuery-layout so that it can vertically size itself appropriately without javascript (since this resize sometimes fails to do so with jQuery-layout).
This PR also includes a minor fix to allow vertical scroll when the content overflows in the results pane.
One subtle glitch is that if you zoom in a LOT, then attempting to resize the result canvas to be smaller (drag mouse on the separator) sometimes catches in the middle and doesn't resize further. See, e.g., this GIF:
When zooming back out, it behaves fine. WDYT?
Further notes:
1. One can implement lighter-weight resizable sections using the [CSS resize property](https://developer.mozilla.org/en-US/docs/Web/CSS/resize) that might make it easier to control the …
> Move toolbar out of jQuery-layout and allow line-wrapping of buttons.

- base.sh
Fixes the following error : 
```
base.sh: line 52: setgreen: unbound variable
```
when running install on a non color capable terminal, for example when building a docker image.
> fix(install): initialize color variables for non color capable terminals

- web/blocks.html
- web/css/codeworld.css
- web/env.html
Fixes #748.
Just adds a new `<div>` wrapping the layout content and moves `<body>`'s CSS into that.
> Avoid setting CSS height on body since sweetAlert2 overrides the height.

- web/help/GuideIntro.md
This is already pointed out earlier in the document, but it should be explicitly mentioned when discussing how to close and reopen the guide.
> Guide intro: clarify location of guide button

- web/help/examples.md
> Use an exact value for translation instead of a badly rounded one

- build.sh
If this fails, it writes the error to stdout instead of stderr.
Detect this and print the output if this happens.
> Show CodeMirror compress error

- web/css/codeworld-cm.css
Currently, we only load the normal Source Code Pro font, but we use the
bold version in some places anyway. This results in browsers making up
a bold variant, which is done inconsistently and often with bad metrics.
Load the actual bold variant instead. Fixes #812.
> Load the actual Source Code Pro Bold font

- web/css/codeworld-cm.css
This fixes part of #812, and also fixes vertical line spacing changing
due to parentheses.
> Use CSS transforms instead of playing with font-size for brackets

- README.md
Hello,
I was going through the README file when I found that there was a missing link to an issue. Hence the change. Hope this addition is helpful.
Thanks.
> Added link to the actual issue

- web/js/codeworld.js
This bug occurred because `showLoading()` disables the cancel button when invoked
> Closes #885

- build.sh
- third_party/MaterialDesign/content-copy.svg
- third_party/MaterialDesign/content-cut.svg
- third_party/MaterialDesign/content-paste.svg
- third_party/MaterialDesign/content-save.svg
- third_party/MaterialDesign/magnify.svg
- third_party/MaterialDesign/redo.svg
- third_party/MaterialDesign/undo.svg
- third_party/codemirror-buttons/LICENSE.md
- third_party/codemirror-buttons/LOCAL_CHANGES.diff
- third_party/codemirror-buttons/buttons.js
- web/css/codeworld-cm.css
- web/env.html
- web/ims/content-copy.svg
- web/ims/content-cut.svg
- web/ims/content-paste.svg
- web/ims/content-save.svg
- web/ims/magnify.svg
- web/ims/redo.svg
- web/ims/undo.svg
- web/js/codemirror-buttons/buttons.js
- web/js/codeworld.js
- web/js/codeworld_shared.js
closes #883
Previous attempt broke scrolling due to change editor position from `absolute` to `relative`. But just return to `absolute` and moving editor down was not enough, addons/display/panel.js (requirement for buttons.js) contain own resizing logic for editor field, which looks bad.
I threw away panel.js, and took from it only several lines we really need.
> Tooltip pane

- codeworld-auth/codeworld-auth.cabal
- codeworld-auth/src/CodeWorld/Auth/Http.hs
- codeworld-auth/src/CodeWorld/Auth/Token.hs
Quick note: Because the signature of `encodeSigned` changes from `Signer -> JWTClaimsSet -> JSON` in previous JWT versions to `Signer -> JOSEHeader -> JWTClaimsSet -> Text` in JWT 0.10, updating to JWT 0.10 means not being able to use previous JWT versions in the cabal file
> Closes #886

- codeworld-base/codeworld-base.cabal
- codeworld-base/src/Extras/Widget.hs
Here is my first attempt at contributing to the Extras library. This module adds a few widgets to allow students to explore parameters in their models. I tried to focus on facilitating learning objectives related to modeling with linear functions, so the widgets by default produce values between 0 and 1, and the students need to write a conversion function to use a different range. Also, the  graphics cannot be customized. I also chose to keep the widgets always on top, unlike the default zoom/play tools in CodeWorld, which hide after a few seconds. The API is reduced to a minimum, after several iterations of removing access points. The interface for the students has been proven to work well (using a very similar interface which is going to be superseded by this one), and the students …
> Extras widget

- codeworld-base/codeworld-base.cabal
- codeworld-base/src/Extras/Cw.hs
- codeworld-base/src/Extras/Util.hs
- web/help/codeworld.shelf
These are a selection of the functions I have in my Extras module. I cleaned them up and chose those that are actually used in other places.
The `recur` and `repeat` functions in Extras.Util may seem redundant, but I need them for other modules. In particular, `repeat` is used in the Turtle graphics module (to be submitted soon), and I wanted to keep it compatible with the way Logo uses it, so that Logo programs are easy to transfer. However, the function that makes sense to me is `recur`, so I wanted to include that too.
I wrote the `forloop` function to address critics who told me that after a year of doing CodeWorld, students do not even know how to do for loops. List comprehensions are not perceived to be the
same thing as *step-by-step* for loops. Surprisingly, it seems that …
> Extras modules

- codeworld-base/src/Extras/Cw.hs
When I showed the new graphed function to the teacher, she immediately requested being able to specify the X and Y scales separately. So, I changed graphed to accommodate that. This is an incompatible change, but nobody should be using it yet, so I guess it is OK.
While I was at it, I also implemented wideGraphed as a proof of concept. I don't want to step on anybody's toes, but I would be happy to go ahead and implement wideCoordinatePlane if you want.
Here is a link to the code that the teacher did immediately after I provided her with the interface:
https://blackeyepeas.phys.lsu.edu/cwn/#Pf93EdrftpZNnpiWXJi4BBQ
> Graphed now takes two separate scaling factors

- web/css/runner.css
I just realized that a small change in the CSS file is all that is needed for having outputs with variable aspect ratios in fullscreen mode (i.e., with links generated by *share without code*). The output fills the browser window as much as possible: When the window is longer in the horizontal direction, the height stays fixed at 20 units while the width adjusts to the size. When the window is longer in the vertical direction, the width stays fixed at 20 units while the height adjusts to the available size. I think this is the behavior you described in #938, which is OK. I would have preferred the height to always stay fixed at 20 units, but I guess this works too.
In normal mode, there is no noticeable difference when using 20x20 drawings. If you have a wider drawing, you can only see …
> Wide aspect (note: this is not an Extras PR)

- codeworld-base/codeworld-base.cabal
- codeworld-base/src/Extras/Colors.hs
- codeworld-base/src/Extras/Cw.hs
- codeworld-base/src/Extras/Turtle.hs
- web/help/codeworld.shelf
Moved the color convenience functions from Extras.Cw to Extras.Colors. Probably very few people, if anyone, were using them, so I better do it now before my new teacher training begins.
I also added a `colorNamed` function that takes X11 color names and also hexadecimal strings. I wanted
to try this with the new cohort, because it seems that I was wrong, and students really like to use color
names. But I would not like to pollute the variable space with lots of pre-defined color variables. I want to
test how this trade-off of using color names works. Yes, it is less safe, but it is just colors, anyway...
And this way CodeWorld students will be able to use the same colors they use in HTML or in other programs.
> Extras.Colors

- codeworld-api/src/CodeWorld/Driver.hs
- codeworld-base/src/Extras/Colors.hs
I adjusted getMouse (for GHCJS) so that it works with arbitrary aspects. Otherwise, the previous change in the CSS file made the fullscreen mode return the wrong mouse location. 
I did not change the blank canvas getMouse because I do not know how that works and did not have time to set up a testing environment for it.
> Bugfix in Driver.hs

- RequirementChecker.md
- codeworld-compiler/src/CodeWorld/Compile/Framework.hs
- codeworld-compiler/src/CodeWorld/Compile/Requirements/Eval.hs
- codeworld-compiler/src/CodeWorld/Compile/Requirements/Language.hs
- codeworld-compiler/src/CodeWorld/Compile/Requirements/Types.hs
This adds two new types of requirement rule to the requirements checker.
The first is line length, which simply takes an integer and fails if any of the lines in the source code are above the length given.
The second is checking for warnings. This can either be strict, in which case it will fail if any warnings arise once the code is compiled, or otherwise a regular expression can be given to provide exceptions to the rule, so it will check for any warnings that do not match the regular expression.
> Two new requirements rules - line length and no warnings

- install.sh
Fixes https://github.com/google/codeworld/issues/976.
This can be reverted once https://gitlab.haskell.org/haskell/ghcup/issues/104 is fixed.
> install.sh: Install hsc2hs via cabal

- install.sh
ghcup now also exposes hsc2hs. See
https://gitlab.haskell.org/haskell/ghcup/commit/c984cafb1c078d42e196196eb21005fda74784d7
This reverts commit 5d33d9ace627f84d8d8df4f1c00c3f9306ab4ef6.
> Revert "install.sh: Install hsc2hs via cabal"

- install.sh
The installation from source doesn't seem necessary.
> install.sh: Simply use ghc-up's cabal-install

- codeworld-api/codeworld-api.cabal
> codeworld-api: Remove dependency on random-shuffle

- web/help/examples-haskell.md
- web/help/haskell.shelf
Hello! This PR adds CodeWorld Haskell examples to the documentation. I know the examples run but I haven't found a way to only build the documentation and I'm not sure I can install npm on my work machine so I haven't been able to test the rendering of the markdown and the integration in `haskell.shelf`. Please let me know if you'd like me to test it and I'll try to find some personal machine that's powerful enough to build all of this :)
> Add codeworld haskell examples to the documentation

- codeworld-api/src/CodeWorld/Driver.hs
This fixes the issue https://github.com/google/codeworld/issues/1062 for me locally. I'm not 100% sure if this is the right place to apply the fix. But this was the main difference I found between ghcjs-based impl (it's calling clear screen before drawing each drawing) and blank-canvas based impl, which wasn't calling it anywhere..
> Clear screen before drawing new Drawing in blank-canvas backend

- codeworld-compiler/codeworld-compiler.cabal
- codeworld-compiler/src/CodeWorld/Compile/Framework.hs
Upgrade ghc-lib-parser compatibility to latest version, by updating 'Platform`  reference to 'GHC.Platform'
Fixes https://github.com/google/codeworld/issues/1100
TESTED=Ran `cabal install codeworld-compiler` with this change, and  verified that it fails with  `ghc-lib-parser` unbounded (upgraded) and referring `Platform', and succeeds with `ghc-lib-parser` unbounded and referring `GHC.Platform`.
>  Upgrade ghc-lib-parser compatibility to latest version

- build.sh
- install.sh
* Freeze versions of hackage, install-cabal, and ghcjs
* Add pkg-config which is reported as missing by cabal-install
This should help (by avoiding cabal-3.0 for now) with #1176, #1178.
> Make install.sh more reproducible

- install.sh
With this change I can completely `./install.sh` successfully
> Use an old snapshot of ghcjs to avoid #1184

- install.sh
Resolves a problem when starting from pristine debian:stable
Installing library in /codeworld/build/.ghcup/ghc/8.6.5/lib/ghc-8.6.5/ghc-8.6.5
"/codeworld/build/.ghcup/ghc/8.6.5/lib/ghc-8.6.5/bin/ghc-pkg" --force --global-package-db "/codeworld/build/.ghcup/ghc/8.6.5/lib/ghc-8.6.5/package.conf.d" update rts/dist/package.conf.install
/codeworld/build/.ghcup/ghc/8.6.5/lib/ghc-8.6.5/bin/ghc-pkg: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
make[1]: *** [ghc.mk:991: install_packages] Error 127
make: *** [Makefile:51: install] Error 2
Failed to install, consider updating this script via: ghcup upgrade
The command '/bin/sh -c ./install.sh' returned a non-zero code: 2
> Install missing libncurses5

- .travis.yml
https://github.com/google/codeworld/issues/1229
I'm not certain this will make Travis CI reliable.  The multiple stages to build dependencies were probably redundant.  I have consolidated those.  Maybe those caused some sort of collision which made package `text` unavailable.
If it persists we can disable caching entirely (50+ minutes per build, then?)  Hopefully we won't have to resort to disabling concurrent builds.
> attempt to make Travis CI reliable

- .travis.yml
- codeworld-base/codeworld-base.cabal
- codeworld-base/src/Internal/Truth.hs
- stack.yaml
Part of https://github.com/google/codeworld/pull/1241
Subsumes https://github.com/google/codeworld/pull/1246
Also, Stack can compile and test `codeworld-base` now, without GHCJS.  I haven't considered if the use of `ghcjs-base-stub` causes any problems here.
> Travis CI configuration refactor

- .gitignore
- cabal.project
- codeworld-compiler/codeworld-compiler.cabal
- codeworld-compiler/src/CodeWorld/Compile/Requirements/LegacyLanguage.hs
`cabal new-build all` works.  
`cabal new-test all` compiles but the `codeworld-compiler` module tests have other problems, unrelated to the `cabal.project` file as far as I can tell.
> Cabal project file

- .travis.yml
I believe this particular failure https://travis-ci.org/google/codeworld/jobs/630081765#L372-L408 can be prevented by this PR.  `stack setup --reinstall` was already used elsewhere in the Travis config but not in this failing stage.
I can't explain why some things are cached successfully,
```
10.34s$ travis_retry eval $"stack upgrade --binary-only ; sleep 10"
Current Stack version: 2.1.3, available download version: 2.1.3
Skipping binary upgrade, you are already running the most recent version
```
(presumably not Stack from Ubuntu 18.04 image)
and other things are not:
```
Looked for sandboxed compiler named one of: ["ghc-8.6.5","ghc"]
Could not find it on the paths ["/home/travis/.stack/programs/x86_64-linux/ghc-8.6.5/bin/"]
```
> Stack reinstalls GHC in Travis

- codeworld-compiler/src/CodeWorld/Compile/Requirements/Eval.hs
- stack.yaml
This PR fixes this warning from Stack: https://travis-ci.org/google/codeworld/jobs/631590420#L453-L485
and also fixes an unrelated warning about an unused `checkRule` case.
> fix Stack compilation warning about multiple versions of dependency

- .travis.yml
I probably ought to stop trying to fix these brittle Travis stages to set up GHCJS, and instead think about something like Miso's config: https://github.com/dmjio/miso/blob/master/.travis.yml
I'm aware of issues such as https://github.com/google/codeworld/issues/1182 which discuss Nix, and also of the patch required https://github.com/google/codeworld/blob/43d26a64a8c6b6279a314741a51cb04a1935e465/install.sh#L221 which might complicate copying Miso's config.
> disable Travis CI GHCJS stages

- web/blocks.html
- web/env.html
- web/js/codeworld.js
- web/js/codeworld_shared.js
- web/js/funblocks.js
- web/js/utils/directoryTree.js
- web/js/utils/index.js
This commit eliminates `window.openProjectName` property. Rely on directory tree state to determine the name of the currently open project instead.
> Use directory tree state as a single source of truth.

- .eslintrc.yml
- .githooks/pre-commit
- format.sh
- install.sh
I ended up using the [script](https://prettier.io/docs/en/precommit.html#option-6-bash-script) provided by the Prettier team.
It's worth noting that I removed the following part:
`[ -z "$FILES" ] && exit 0`
It caused the script to terminate early without actually doing anything useful. What is the purpose of this statement? Is it important to have it?
Tested on JS, CSS and HTML files. Please verify with Haskell files. Please also let me know if something could be improved as I'm not very fluent in bash scripting.
> Set up formatting&linting in pre-commit hook (#1375)

- codeworld-api/codeworld-api.cabal
this only bumps those needed for `codeworld-api` in GHC (non-GHCJS)
mode; not any of the others. This fixes #1466.
(It compiled fine, no other tests performed.)
> codeworld-api: Bump dependencies to allow GHC-8.8

- codeworld-account/codeworld-account.cabal
- codeworld-auth/codeworld-auth.cabal
- codeworld-server/codeworld-server.cabal
- install.sh
As the node js version 12 is deprecated, the package manager of the project is not allowing depreciated package's to install so the installation process stops at the initial stages itself, made a proper documentation to explain it to the developer and additionally added commented scripts for this action
* **Node.js 12 Deprecation Fix**: Updated the project to accommodate the deprecation of Node.js 12, enabling the installation of compatible dependencies.
* **Dependency Updates**: Resolved build-time issues by updating dependencies to their latest compatible versions.
* Added commented scripts for reference.
* Documented the changes for future reference.
If you encounter any issues with these changes, please don't hesitate to reach out.
->alphamoris45@gmail.com
> Some minor fixation to solve the dependency issues
